[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "238f3fcf67d990623dcf1e4f709072bd6206b045"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "6cba94a0988210d374952bfe5c235308656dc8acbad862d1c0704e4a0f054e59"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab4ce4b7f6d58ef6b84c1360d9aea7f0b44a4c8"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f6145609bf38830657435c4d8cd8ac0a01320f9e66bddf75dd23f9290773a7d4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8b8a1762a5f79de71c945fe21e5d5e8f1da5fd4"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "d6d4da0462e1fa48bb54546747ed03bda99c3f94bfe5a64c5f94cc000947fa48"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "420cda7fc3a5966a1ff65a379ae285ab5f289513"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "7c4e9df11411b734624cf766a2df1b90e3d82d0ee238d7b9f861655afd659d33"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba7d53f15ff0002f5caf96db6af7140845a0db6d"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b4ba1f41b8a1e8e500d4e3f571840a4d3cee88288b479399c4301a8585b6cece"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "545336d000eb494d81b80a40305d771ef42cdc91"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "932a85850fce03aa97ce461679b5c2fa51311cbafe44569bfe0517fab803cee5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.aarch64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74f382f2fea8e5f2da1ecee13203db94c5d59171"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9c7e4b52e260912a22e55833a18bed1052230896f50b49b5b21857befa44fa1a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d163970ee205451c286d8a11cc55b7d018fe5842"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "32c6a7a0f415e2230874388e4462f9e08d710eb0bf4d6fdc773e254697770269"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e9249308a4c81bf7d6e0ea593e4c1affafa7b03"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "dc6ae6de4d8332fa187d61eeef6d553a1f917bb2ee77e364e7c07e519c3cd98d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0f6e9fe9050cd79e682c61201d4b0588a246ec2"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2f6272482f6230c0caac91483a6c4a20a546e2df91830d6dcffc975f3182d27c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1799f8558161573bfd1f66dcd6ce249ba7774ef4"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6358f1fb58997ac577c9985ca5ca28c4042c917692bb6b69872e1453a9dea363"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb69b8bbdfb6f46ee105ee4dcea4e6e417156419"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ba423d2348879959caebbb41d69d1d2f9c5d55823c913f5c9c700582c0e9ec32"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0622bbea2d9c89ebf8ca820b204f1cd926e00504"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2bbcc016591c04ad27be8d9e587f8eeb1b80bd465f487951efb930d135289ca0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c58d6d4bf64105f277ba4447ae6476474230317"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "8c740125440c019baae1369af965dd1a06d473cfe4c8d5446b8a9baa91fce658"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f38a7e009b6cc17ae682c46e3a041af5f8b49284"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "50dd187e9ff7afc896d980b81b3cd506eb66f075ec38a8e4a18fab091c72d272"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96700bec07e74a6c9c3775a3238c7eb7658bc364"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e3c96f943e961458415267a50f97bace4857f57d96f5b9049de461c4f2ba23c7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfafff66ec54cbd8ad5f0bdd7e67bcff8d9a8014"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a3ab182d4f3220138f6a927053cc9f620630fb3178cc59389bb82dc30d9d5119"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37b1b200ebf1b0e2f577fb6f22cb0096c80b201a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "75d9811481ae153f831df9729769810ac1f2de91772773907361c84ee67ba26f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "3a219d2834a828cda54c3fe2d958d8f8df490fd3"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "8fadf729694ffb96fca004cd0b80cc8ed2a2dea24de0ff1ba5cfee9751b2f9ed"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08b24813b96043808403b633203c5a1d9fc60931"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1e0c2b3f9df970d7354e84ae7d25697493f2e94fdee24c516b9e6b7562199a12"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ef22077b29d1fcfadacceba699b6af59f882fc4"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3215e7c4408d69397045f1e68a3b0be1655ad040789b5ea1406ac4257e0bd632"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "17b92432d356cc57ed8d09406e15d31ad561fab3"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "0a587b6110b3401b99159bbc15b7f63f832478739c7d02891d4757cfdd2e0618"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3e792dda1c6a890a93679df0f903457eb49bed5"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "90582fe92dd6c7445fbe6aa5964f2b0ec62f65091ff4babdd709ad81604e8467"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e821ea6a33796b69fa07ee18c0468c555919c7d"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b0ff8cb224a1366aa016092fd93024857eb20f1248b37778b603382ee1a4ab91"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dba81f4012990b521e7837b85b58b9dbef9341d"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "60ebec94a3a79df1b445c58ef8eaef4809fe59cd89598d815f6e1ea258254555"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc620267dd9fae70f682cc03a8d39e793975d60a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f4c2ad223ed90bc934d47f4928ef69fca34ed1f1f06ddf48aa8e75c08467d5bf"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "1187889378ab3cb2ec19c31783c31d80668544c4"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "758183f00a2763069709c3c6be90d11ef3d62cf61170b73e28fde9fa15dd8c82"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "a4774f07f0fe6ff8482cb16fd62a576a429fd19e"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "140c56cf72a6368060724a36f0611c3b42523962b48177a34a69d593667482ee"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0+0/HiGHSstatic.v1.10.0.x86_64-w64-mingw32.tar.gz"
