[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "cb5f90e846d6a31607a2060ce794332dbd5a3979"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "91625662efd13074e4a1a5241d304abc1c6a948260857ef93b9bf504bf511f2f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9257c314dd77b76426eb6bb2640f0993fd2fe21"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "8c30a9fe9f0c5e8376277a2e3ece458ca3ee8b4ffcb77a21486ab2f8eda9955a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a737767b70fff6a6fcabc7ec07abc0177e2c8e5"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9af1d68d0c3bcb393ad9df4d96953bc54d4dc47f0bde3bea22a2f32bd38629e6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ca92c3178fbc04f637cfd33c082e339b1e1a754"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c44252ecbba370337aedba5779c2bb434224bb74279dc0f0bf5343937978c76b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "028991014fe6be7b1b229e1641a844eb9b2f633a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "67cb3357e5e15096250fecfb8ff1d8fb3606b0f4826b091fa311f8975af2bdb6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "f370026b90b2da011c26619cf6d9eb8866f6352b"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "cc201771dac3cf5265f8a4f382d25144126d7af40dde18136b58cadb980826f9"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.aarch64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4dda109ea66c34baee1e20b9fc49813d088b2daf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f0d8771c792043e5204e899c06b57b9c570287dc154507a0848be7a21ba8f763"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e50044ab4fb9ee5e6d248309b7525ff63b406d1f"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5a624f58f9d76d4b4965cd969e8f0aa7b5a333990d4845ea0b5855f9e046e121"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f097954ed7fbb397244edad853c91280a819a183"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "05ec4d96d1d0922968decbc74a020e84513082b4a378874f97c1385f296d4925"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9ede7833a3a35035b7b426335a56bbbdb8a2597"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bbe644b619835bba6de47d52db96a01782065cf17ac0d50eb6502338132a64bc"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7051e3fa89f657a3fd7a58bb84e266c3ed72c7d"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "72ccdf06bed87cc0b6c66128a009a071bcd4e12e42b8f9068bd1a51c333400c4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82599fead61287f0dc68bb220d27f122b288ef01"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bb94403a8462e5ffb937aab40c87625eaf351dfe27826ccfd13adbd8439e93dc"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f321f15494386fc5a556663221afb31c323ad13b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bc3b3a34a7d1606f5f4b9b9d09191a5878f69b936b23eff58113d41473d4efc6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d2ef717255dc7131d68b52321bb213fb6308e29"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2618cb48f7da20ad9a912e378816cfc6d3e5de83c930f8af1163149affd118dd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20389f686ea2b7bba9b849b877dc1423556e4b4a"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3d5dc680cdb09567c915224ad5623d0d0d187e92a0b03308fa63dabea8efdba3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c626482962f3894214d7d0111b844532b6d4bb2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "442fd4fbe40d278769788f64b316f5ad11d0a12a285bb709683f8a81ffd39adb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93d920e361de55e85053dcbe92ddd6aaa2a54cd3"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9139c7d4c32dc7956f5a4466abad007f1c39905b6472ffff01457b2552d72bc5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfee7af1590ecc6f7060bc413070671aff4775e1"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "cc529425f70ce2ae1cd2abbf08ed17cb53efd5c5104007a67cfdbad122ef0b65"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "faa9589e35f52d508f3b7c62b704ab6982c3667a"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "739850be3f88068790bc64231618e71ed07885d69eed285738b70db670b192ed"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca145cd1bcceb702898dc99988bfbff2aba1ec27"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9ffaa8ed0ea17b6f6c3c1394281a5d1cafa8b9441a667bc19c39687f9b25f9c4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd8eccdd3e20f8f51b877a5b08d38333434fa189"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "04829662f5e42eac2126953edb3cf980ac9cac3f1ec84704ee1955df26b35b82"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "2b6c69229df46fb86c47399b6bc0f46220a55cd5"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "cf7d9b1ef44965a6d36d0a05f963a0ca38bfcf65dff8c5752dbeda3221922848"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffbd8b58958a54771a328627426a45688df550ef"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e58756a84a23ee29a86c119ce31d83dfeda8c1bd732af0d65c70d821b2a8b94c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df6d39f8b060e635f9f1dc0683becb2ea272af56"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "05c1bb3942df604c157a5fd78300f176315383e96808f2f0f1eac0b3cd753194"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "620ca5a6e7470da4493166c24e6db52504ce4078"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "08239551e61926ff1eb10a6984c4d9402fc56e5b4036a1cf1a0cfce2b752265a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cf9b250bb9db59ad297ff0cf44f2ee7ab3a0507"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0d4171ab0bd6123f275a3b666cceefcd6e86b789ec8180d103a9ab297901e891"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "4d9c29cdf118551abda44ed399b10e57e6f9f197"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "3dca2dbf6e91b08ac220df0c8712fb414391fc0aa9b891533d897470747be80b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "8bdac2f774805d30645807700b9c708a8cb3d485"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "8d81e64c747ac44b7f4ceb09ad97a1bfe18381dabd6c2092144a183636f26450"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.11.0+0/HiGHSstatic.v1.11.0.x86_64-w64-mingw32.tar.gz"
