[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "1d00ea23c62ce01e835f01692c251278fc1250c5"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "633769ddaff2d844d84f74b3a54eb117421f278f34385cbcaa7d0a9d66bc4eff"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ededb47b325411d7b81a4963b70066f6a227f99"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b659462cc7dd545c3dac7dffc3078e8707f93915a317e75031ef11936f36edf1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "112767e45ba4b3de6c64d6d0e7b35b315076b4da"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4e6effa3ffe9acc8a0641b32b5fb96ccbad96874c518b49af5f49ce3ad3b22c0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50babe3e145a3ab6bbe0316b15b3988915aa6b31"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0a0a334f430cde3fac7f494388ac3cdce552d90c41bbd70410ffc0a47e9e5515"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68238e9a6b2413d9880c890ca59cdeb2d29c4bc2"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ba593038c920232e4a5c41fbc5f24c92d70827d951e4ecfb5493270743194eec"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99001b189edc985d5d68fc12e8afae73b4b41965"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4be80d90293c157264fcc6b9189dc1a33c1eee0ca998c99ceb4f965c7c48fafb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb885064de8bc62e285a42f40427b89d9ce1aa1"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c6ede83d1628277fa89d9e105b003ea10702ef72880e271bb556022ebeea5233"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "458431f8b9f855747e8492085b49e2aa33aa5199"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "922da3a3443ee8b504ff08a06276df7c72ad2e28b3d851661983faf4ac76b2bc"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35f0b8accf6ede085a866dc5f6384c8f30e6fcfe"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "14fb6ecb3ec3783e96c72b35ced85d11b3f8a71e8fe563ec68a438b61aeb811f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "042ffdb473bcea9c59873f1cf44e852d9d7f22b9"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2a1412f6965024960a14a8507c32fe4db30d423c0ba92c455983e67d9a5ad77e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b647f3be59fc07d304753b674eb21ebb39c9457f"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a95902a8275631987e2fab8b10c0bf282a6862ba2527e9d2c4007711b1f37604"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "061a2f5b21c4a52ee36cdd0816a4513677109661"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4eac22eb379c9b3f2e6067d5d26655cd7f197f0914ded8dd9251ff5b2b1e2d99"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fccc3226dbc1addbea1c9beb9bbf9c670fb03919"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0c8309cc2358946f09e7a87ea9b84ec3614d73575f998264e70cb828ffafd74e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "351bf6a7efaebe153b2b0ebb03c4cc2a1d46a98b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1f8fdf370bb1b02a75580c08cae60c58a60616acd1643cdad8decd188d136d4b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67d7f95b08ff9517770e926be18c509ee01d8113"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b5c70d8be24284024e5817e99983b81db1113ac0934b8fb85241a1d43c8b3890"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4b4c1c93d88bcaa2b1f1bfe78928b957d8430a6"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "065e813daac7294452149ab29d3527c4d59ff5ca915176fa3216a31dfb1da6b0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53bd34f086faccf5cda67058cc4336987dbb7940"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1620c355379a7131182044bd7c65bfb02779bc40cd059b27c0ff7cc5a48d38b1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "a9fcafb8e3bed4075c292102ef19b4921be002b1"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "9b88209cd4990c0d81818c2aea00cd293b8ba2285be7d428b5172f90abb056df"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7db233d30fd4c6874466284a72308cad8b81540b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0ca8a775a5b8b093e343f0b492f0d1f6f00536920c5035e749058bc97f1dd3f7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4757d51b2462eb91b9b8e5219cdff1cd8b671bf9"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "303c613cc3d346ef923f542c7adeb43f1cf56185042b67d9bb43eb02dbabf494"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "4ce36ea7e5ed3df177bf3c916dbc165cb0c67f17"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "92df0523e56f809f91e844a01a6f35e1ae03090d2ba6cb5211922cce1b9b1ae4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dae074f485455438b454b787d060419769b6b0c7"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "05bd5f02780639ad8bd60e5f2bc48880bbcfe906249f305df263f93051403287"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb459753b840528384cbd46dc977d9aceeb2b257"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5314d57ea4c6486b0dc1351426160f59a4074d809d2dfa5472d0b142c81cc651"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e081459259069ba9d2a0a16c1542bfa4165c1f2a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a33aa2c289c70a99d984d77f1330eed8f8d4a8005fac67eb413bbde8eaeaeaca"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "501f74c307d522967cdf96b5385e4d30c12b698a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "451c563caf5f4b7e49ab821341077259f692707d577f176c3ced783c961a374b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "83bc3e2f8e0db715a087a2a073103072716b351a"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "ed569b775b87feb24492975e4226182853cd1c8ccdfd3c724f6d9d351adad637"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "fe347cbba7b31397dc5c55f9131953818d38cc86"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "25ab643e20ac1ea5488bc526ba296ad54db5f2a495d4b6e114d184f63a739fd9"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.2.2+0/HiGHSstatic.v1.2.2.x86_64-w64-mingw32.tar.gz"
