[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "b5737ed2d9955511bfc5cda0393b5d5d19e7c741"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "c1dd5ec0ecfcb4cfbfb0eb622db1d522aa3efb44762b76e90e4b444a9d021dd8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad8b84a7ace13b09a0e4baadc560397a0f5af990"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bd5ed9561ab1aa6ecab13454c30176b2813a7c0e04bb7b6db7726a2d7c917410"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ca0832e66d72710f55932491c11407e6decc355"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9e0342e56d467369bee004c2ce86278a01dc011d643f2234b8e4cc1cb2b7539e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c726bdf87d71a44accb77d2e38dbd1857729e742"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c61d576fc88c4db21ac574d5af870d4758b7f97f134c5fd130d00d38fb1c734b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65e0daaef36999ee7f1ee0f5134a4fc7a52efcd8"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ab9999e46d72003375b7d1ec0dc23d70679cfe10e791fef8c721a3c594b16042"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e89536fa4e80508d7fcff5057e0c634d80c967a"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e66d3a409e599f61c0e70272e53763742836eedc133d4d98231df48d111ab864"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19c5ad93f773320ed3ee135427baca6a10709d0f"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c62d94c65699ef5c06b4d642c9742c629401556f28852f310f5a75949f89252b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd945a6c9d4992379ccfc499d80b3e4394be2cf7"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ff7d326e4b09f536badf308db3de0896bacb8a85c51b21daed2cef9b8e9f74b2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39af2ac3b0d77198b217000c1fe27f6980a2720b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "24112d2af9b60e01c55c73e6529aae45023d7dc0407c43f6f499af4078f04f75"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "897bca14149b74d54e2a54af69543bd0aaf69920"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ecf7cf1ef6fca35f7386e59a8cd890bc43acd5c70790a3144f4c95884be79ae8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "528dab0a3653fd4618718cd57cee7b634ae769e1"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5666e1a06f26e9ed1a85bb411baab0f9db8d225f90b16de2b9bde58087d6023c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59b4300246d016dd138e3181633be256f768d648"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "30756fc519a3a8d7b038dbf8911be021778df5d40ed6529562e5807ccbbe9f07"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192aaf21d0c9515fa1d83eb69e900558686bb9d0"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1924125878ccaf0808e3c3a54d2ba730b11426ea1cb6f3d1f572d215af1b51d3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "202a37b444ff81549fc60b1c001e57a7e2ad6bf3"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "fdbedc394842dfef1a52125b9e9dfa8ade0760fb6ed5cc0cceb1623504747bab"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29b35675997330e21282442316929c6a02e1c9fc"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "befb89870ce819503b3f152d420a69ca585404ba5c0b1d188269fece31146887"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b51587205bbbf63105bb10988051f6c2f4b0b1a9"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5ced3003b344bee78665fe637161545547b2829b56dd16bde559940dd3c7fc46"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0a1520649a48e16a13d5a91c866ddcdea7c9c11"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "39ba479c7ceb0a0c1fc79fd565ca6c85ca7609a8a62ad9b363b41f0bddc2e4fd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "ce28090ee6ae27eb7cb52b8c60325eaffb7f594b"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "8c7b1e6ff437c3c53b2620f2cb007e2bc18a51c94014f09b4435926e4814a250"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce1ede1fe2592ca629571d9e667add85d1223610"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1ca9897f880c9f744080c78b874eccfd568858dee8e0c11c09f24009114c9f0e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa7c56ff4e5a7383531191aeab1087d56ecae4bb"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e5d366510905cd5fe498aa72552d693f2b66b57084bb3b53185980419d1c49ee"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "3646ceb8b36045ac483b485a4f48188e43eb3aff"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "3c60d001c7ac71c43f8cc36309b1223fb846ac781bdca51ffadc53ebca268e50"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d983fdd527973a8227135cda9e44661ff8d74693"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0708b4ec22bef80bb6d0d103bb4f1e7a20df529bf61a7a7114a16af54d0320ec"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87ac3561ac9f4178664a17536f528c8e7784feaa"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "412b979439618043f363fff044241dc9536519a17ab77ebb84962ad338c55d38"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29a03ae228f7d82bafb4230c23e84a9831ebeb1c"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ebce037fe5046b640660c02e6c4476adff1fe52cd414d7b4062f1b061f81ae1d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09b6e4c60dc48f9e2aab78d6366985fdc013ea93"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b704ae4fb5a2f2a4c538743174028e4c95f9c9dee5bd95709dd255947e516315"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "c9b2756c8523d41f18b12607bd6dd40a447be3c6"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "837406390398db5b07c66e3087363ab506b32b9babb38b8aefcaa1981ae6253f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "52e2caa6a146ed6d39a43a67ba900e0381f9e2dd"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "0bffbe2c7f5f4a5ac38ca8e667085f638770d56a612a9f46e3142b7f2d962ff7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.1+0/HiGHSstatic.v1.7.1.x86_64-w64-mingw32.tar.gz"
