[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "bbf301dcc83f738e90ae283091fd3f749843cdfe"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "1a584cdc65aec4c0488273191c7be226825754ebd43680c143dfe4c6f1c59a5c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96c26e71acbbb52f37006e699cc4b41e9ee099ae"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5f61f41182f918a629dffaa867310d83a1bb65ea084eaef580f8f5b1cd5a40a5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88f4e6cce0469479d22c61d56efdc98397ea2b47"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "92bef29ab96fdae72f3589b7fe7e9429b2f363a03ce18a13035c643317a0721b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a22627967df05614cada3000c32698c5b28df98"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "23563a63e74b2e495b2bba917c949730d1010f8d633e8ec70b5ebf48deaf999d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ca1423f81dc1e062b6e390f62423acf756b3081"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6b04dde0c1cfd654f371a3de234f5b0499b2e558ff8fbbeb41a080d5fd5ac5a0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e742c54b8a051067cad3634687be59b6a0b3e63"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f2eb995c94c2cc2ba5a085218060d4ed139d37be87840a7548919fd083f2d9f1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57f2b83f3929e3f25953db0108d036a56f262baf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2fd5eafa3ddbef42bfb4d8d02868ba0cf4fce31ae466aed0be651c7753bdcd91"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b318152c44d759c862ced20753045b127825265"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4bf0b186e1e928fab88fc7b4d398fd7dc6e24c111f9a16bc5f848fa14f821e1a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f090d0229396cdded8224862f65ef942d60036d6"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "516dbe83bac9d039a4cadb93687a43080faefe20b20493ced8273146ef714ff3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98c746c027b17f77c16b8537d37c454c620dd7a9"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "08e9d969718f506e0bcc7cb1e117254f21a059c7df9c9af48c88acc2323dd96b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c5f5fbb755ca31dc1d137f8da795e0a5cd842f2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1e23eadfcdf0e30a5738635a835916d386ac971fcf3ff516ff13317eec2bf9fb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd4c62533d4dbc977d5e4be1f81e2d159d6700be"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a85f2958f58a3802abc5c72f60ee739c14056c0eeb307bac43c0fa5fb2c9ff74"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "334ca272ad69c59b7f7673d2b76de3e9d724d040"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ad2e0f0a97edc52436415996106d578065023182f487fced2d5955fcd8798643"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0345e0df93060f10dca7596c5ba91d40a7081649"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "05154f0f7313ff357aa84f52d877bb887b83accad491caa13131b66785ef95ac"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81c143f6241294dd1901d5c2bdcba05532492e15"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3671e9585ddc27bc8603a705814606647e9a4f3654423e0f60bd2e204e8dc9e1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35b82002316364beca8d684aef1ca3eee583f9b3"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2daef43e842f9694788bd623ece56ba87dbe3cf97aa943a80d43f1ddb252c578"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dea2bf3f9dd4f3fef5890ecf79acae2099727d28"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "960404f36c198033fc3f5758c7b9dbf545030fe5e40b1c0af5ac231a8b7d9ce1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "e3cc50fe0d273fd9f393e25665ad363a8f576f4b"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "17349a4c161ef46bc63c127a2cddfb5af7d0a48c094c13b58e28e6537fee9594"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e87de416e2dbdd09baacb9c371b2b0462b2d3f26"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bfc1f2bb100b737f3b8bab28ee431cc6e7b70a0ed4d042b7d21d73f5812663d8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bd72e931349a2b604311937667425a5860f6c77"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "8576a25973d7811758f89d28d0297d698cabb1ebb2808801ae46753958c7dc52"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "743befd7f6b5172a06535acac9da7c84f381a785"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "f7c6001853be8d6ff4a2987a59b5639f484e8d6d59e6ac101857933cd2d09d59"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a3bed7b96f1d8a73707f8becc85f22c0fd957ae"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1da3f866d806f1acd0d41133075bbd8e9eba7993b0e36ec9686c0ecb6240ae77"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24c8714f9364c3054cfc773b02511914cdd22d8d"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9bf55e6e9e47fd4f01791985837b2aeca3f0df909a4f513ccd04f906cfd8299a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8445b3c2bc8e357b88f96c571365769e9337fc0a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1cb2f4990c1e4646c84676bd728cf9c0c10cabfecb71d38871c25a84a0900230"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4ed377535daca6fd786a328580ce7a1b3e8db81"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "60f820cd67f09e59b1c25714e6028f24989c47f42a01e9190f6c9120c8c98a0a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "8b0ed5e5d2921876ff60f11f55bd8b7b618dc79a"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "cca3197585efa98a6cf3d4b73475c183d59b2bf57eeb4f53b2dfa40a409e63ca"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "5e0cdb5819c5bf909aa4de59ba4e49e8952ddf61"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "6794e8f19ff81523499678fbcf690691aa6b8bb974a7009f6ab21e3848da3e67"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.3.0+0/HiGHSstatic.v1.3.0.x86_64-w64-mingw32.tar.gz"
