[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "91c06180a64ca3ddccc8d249a5ebbc371cd7ca02"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "c52f8aae018878d4af75087d64871ea5f7ea06417440551004db21418f4ec6f5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9add2972da1a7030e54dcd314479a723ef5c5637"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3ab2d8f50cbbe77ca8fa1500704b6938d5655578adfbf312bfe8249aabe7c041"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3998c8912d435a0f0dbcc3b957057bcf8cb42251"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2162f514d72058a35e89d51c6d01f09a8afff873413500b492c8d16e505097ff"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a99a084bf8b2b117725ece2a5f858a4612e030"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9111a249a4e01aa3fab9cf688781fa26d52dc4251a5118852c49f058c9d6615d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0a29042b26619c57397c7369480b26c7e5bb97e"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e15a9c66b7df646caa41e9cc834a8299dc8650ad00e022a58faecbf1b90f83e3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b051dbb2794a989b1742fef0e60879f0de2fb13"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a0aa2124133afb59ba7f4fd49c187d5ab34a5cee008f7447e8da0f0e6dc1ed58"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b418e640522066400411c57d9e61680ce6c255c"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "da71b0007fca3d613b0426b1abc7d0bfd892ffdd6a67a224b034bef6c3a550dd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "349d5994b88a50861e6632307727210c73d6b9b7"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6f4c181836d4b7ac53c7fe7d256c7eb573ad37cbd856554604e1a96d4a4a6b1d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "245e05bdbd4db686600575da642546caefc13af2"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "48c846161fd20eb3ebb71b5bcc3a6ea2cf053f54a3eef60b90374564a8d73409"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66b1fec6f0dbdbb2dc81b9fd9f87a27e54f113cf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2c20d83412e0d35b0b26385a3fdcab864e4aafe0d98d575b85b5f6083ff65d2d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a197c9aaacb48c5736bec0cc05daf30f11bb4ae8"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6ac74dee9d5a6fe9a1a77016961e6d63064bd3e23ca0b2d5a5cc806ef2a5da86"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d553f136e80130f967a193bcfd92f47fbfe73b2c"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1d491010d4c67b1ce1a7606eafe5f6b99401d966c1c361304aaf0a8109bcef24"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c4df6309bb63e7d478986ab8918df80d06d4885"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bf70a836daebc44cc38638d672d5e985f3bb121ce8bb8c4406f67d94322b3236"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da00f687d4ff09a955a1ba900cfef3661573647a"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "104d4cfc4be5985ad37244ae504c99bd5b64f878a6e781ae3b4ed09233b240a1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e84ca4ec40b03938c32dde5d74e4c32eae5d519"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9a1fe01c194417137e6e85e791f9f71cc6c9afcd5b4a5b03aea6d33c7cca72fb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46751a1c447789ffcc70b365cedca234864d3491"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3dd5f92a3fc20fc8b10a97acb41866d3a101ff9221402f553c8903540e30a1d8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fc44a812346a742143904d2e187db25e43a6de5"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "8072fd32365e0edd20faa239bbe6ce48eec6495bba15ec91a94f6e86f5929510"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "e987a2af623bf02e864d222c2df1280749ed2281"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "c4ac08170ff9fca1b1549c4340fe6c00662b45d50a9901d37130eaadaa8d5bea"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "011203fe8989d40caf601e5f6af5a04aed7ac55f"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2c0c33e4ee4ba7a987df658157707d8e913794ffbd2a0a9cc8b03c880029dca1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45bf2c9a7842afa806546a03995c6d5a4f78b8c8"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4d7bf41c09143b3ecd4caad6f2d9df5dc25dc8e5344a61babe752170890cb0de"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "36eaa4d1c471b9aa8bcc54350206970705c87778"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "6024d600e989a0372e56785bf6a11a020b8f06fa4390d83b1f9b54346460e35c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd80ebcaf16f7a6b4c912d15296c64c886994a33"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2cf813a94f97c0adb2b54dbae3a9f047cbf5ef764b06f4fee1c98a537bcd87d1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fb5c03abe0a12917dfd5b40bf673b7c4ce1d60e"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6b8c77f477f9ce385a6b1352b26618aa0f9a262be5261223515945733c90c8ac"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35d5ae38ac0ee536e0ca0981f4751775a5c67674"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ad7f78e8920860c29f7275d40f5cadba4c36aa97cac8fad8628f23df311d9a6d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3ff896c7225836692c89679ef09a7815179fd2c"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "debe96ca3eccf93e06cd39f47c16980984fc2152a8ace09d8d3c75c2f56f3a50"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "e17b22c4a7ad630a9776d94f14ab43dd9a674328"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "42fad79f3dcb4b5ea3146b980d0531bcae3efe8b9f47bb0d0bc3614b6bffafb7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "cb43695299b980e84206c34af5c347b17ebf7e5f"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "b9ccd702f2f3387e408eb4dec7f4c8d0c0fd896815209ed0dbd2231788b787fb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.0+0/HiGHSstatic.v1.4.0.x86_64-w64-mingw32.tar.gz"
