[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "bbd45b14c374e21f3a7b0ca9a3a9f283dc0289de"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "b21a5fa072b5fcfa2b5a88b3481bd31351ef574b2f8ba5d32da833d446ffe330"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86037ca1dbc067a2579019a56cb7a3cb15c08060"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "be1321b8b174defae5e4cea9745cd47868f9c604d2b32fad537b2f47e3478dde"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d17b91cf5997c00446c5d0cd0ed8c14e00cef165"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "eeced131588e6028e10336fe9e7d7a8ad8bc0f2ec29d33bfb6051dd4a2251e4e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb5f1a8b4be7883ef43f01645a5ac10baf304e74"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3ba5e05786d2aa4e5daf6992579505886a27164e588bf0bac1fa90bbb4c421a6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "866432835f6c52ab07396c40b736a7504ef846e5"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bca0d4742f982bab8543a1855c3431c76bf5acbdc41afcc135826a33875908f2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2830d279de04035630cf6d8cf6dde8bce01bcdff"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "21b804555a5c19b7358c585d25ca4e25e7e59d245754a2870a582a786d60ddee"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "736661f72be913cc36c1abef815a040ba0cffff2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "09d2342ef620d4894fd37f2803e52e6ff85282e1db112c3fcadf231e182cd7f3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f39b854a2da404af0565752a1625a8f66df340ed"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f878830416b7529ed35c4d15a8593c37609e792d960cfd0ea58529540946ae09"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01c52ec909620b388fb3b52f552a2bc28b9e2c10"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ef612dcf76faf410fdb86afa5a8c2d930a5e9c6388974f455666f2603e5c6b2f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e0fd0f87fe193a82a028312698549a2eae664bf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "cf7c490c7482a81bebee4ccbb116f856fc317e114eb63f93f69f66acbefcdcd3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff49de86fa32b95da6735ba270f4e6679ced2e6e"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "7f878ffb51874887d17c41946af2dfafc1dcc3f8590bd352c159b6111a95a1fa"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1816cd89861d7f2c14615de1fafbfdb2743315"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "dcc4d82115472c00252c2f81cef32ffb32c733819d1cbd121e1f7a5895ad6fc3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e35d36f8447a43f2e036060121bc9461ac070683"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4eb7c95809ee0c00ac90451e314ed2234ec8432cc6fd702aff981fbf9d8b6fde"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24fccc686eec9e1da20c3ae415b66ac7b0945cea"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1b3b364b9de933ff57d86acd97819bb00cdf407d0e7ea40ce3f3fb37c4681504"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7a95ec12ee7dda40812b230e3bfb28f2e0f38a2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f96c8fbc77a178be456cdd99a60caab88bfc154024eeb6ecc4b09f3893cec141"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7decb80a05fe9dabc043238705173d57d01da2b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "61bb1583452f79ee96e0fbee291ecd70babc3f913034f4d57b1dce8c5f19660f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e26bd840acdd4cf0756bfe88bd98a5bc25e4ecfc"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9b54695fd927280ec53de9de51aaa1d07fc510e03c643f9ce17d6e885de3f706"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "446fefb93f329b6543cc084948614ab69d0e6614"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "2fa74541e70a4c86bc1d0a292015b3e3391f9fcc85efe093c623e85024825992"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4fbc58db1c573c49250b39edc3b7ffc41aa25faf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "d37f6d6add6141996c57be337715fd53d60fc9ddc426b4dbf853a197dc1d46f1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2dd2a9fb7e9710b9d2bb0b467703b1a9fe849ab"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "054a9e34d180d390e12693a5a9ce32c152d2242b74b56d07910016c0177d0ce1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "aa0fa4dd8f985d971f3805c29ffcaa297c00b7e5"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "fdef081b9a33b126281d2de0ce0bf02d8b25d222302949f86478f6c7eeaa76e7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b59d3613382378099e628f54212cc4c502d9453"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "05f490430a185a1f9152ad4636049b638318670a8af6c6ca6b08bf62f54a756c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78573c37d7d1c7359c27cd71e5e44ae0a82ba480"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b2d3e2eaebfd50f065baa43901b0928b059f9cce989732935cda07fdf93889b4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da33ba226e2ece9acfde8b90d4877d6033389c8b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "300199aab62ac373f845648fee74be7ba1a06d0b2fcab6a1cc91a6e83819f482"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80356246a49ed4df44285736b771934da53bf910"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bc047bb4fba2f35f80c444ff3a7ea89ebf72d205f60d321ca44d9df9a94f2b47"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "ed71f65dc08e2406c878a90615c7d51b35368758"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "b29ab13c2f70c19149d710d7c01105491706b575549595525c454ce0b0e386be"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "33b6a6a6f45982be80c1c4467436bb05810dd776"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "89ce38e38ba3c0a647279992ea4f938b0915d6367386c4f4af8db2018af26069"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+1/HiGHSstatic.v1.7.0.x86_64-w64-mingw32.tar.gz"
