[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "b4d798965a4640817502d6c659016f8e0288b482"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "5e3fb806e74b463e3f896a029d22bb0eac827aa628c09259db68c8a0437dad5c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "428a87b7056b3005536f9105700a91473671a783"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e74ece9c7b030c0e13efff7ce0a33a2fed0a1bf89e3ef6256f8586746ea3679d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb98d8bbda513216b33a14b137297238cd025bfb"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "063d354f623c581d59e6ff9c13b637acef4c19a010d717a5a562bb30f960cfc0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3e6b04815f82a3da78aace436622dbee3e144af"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "fdab4386c0400cc0deb8c11cdbb77866a2518ed9fe5d612f34f4b9306faf9068"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08936ed0ce463410bb411b19744599e2797e435b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ee1d4ac0e796b25565800a1db5665477452d4057f3d67e7ead4ea21afd247e61"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "d056b555974041ed0cbebf2bd2834116a96535a2"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "55453c853d86dc7283f611971cb4b4391a4a9d4697eac8765b24f1e7cc611656"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.aarch64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b06a60e5041ba43e7a502c4d028145b9e226d0f6"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1fc10c4761d5f7397109422e8277cd3b197a2420b435fb86c06c80386518764f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b937650a89c134765e4da37261061c9dc89ffcc"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a823437eefb0e21c6326da3a178a068d51c02d821ad751c0501e1e22d2d49aa2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cef6c3701519c94ea2f20620242cbf3c7b502d7"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6cc3aebfcd14da9944d1d1dfa836d25c5114eb0adeda990494d5cb69c727c998"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4764219ac002316c54be172621c6113b0f556341"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "7ea616da86f14d5644b999c714e018389d1dd661a64ca38c06edf2d2c980ab58"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb6b22ef779a6e0788298e79e3699f6e94cdc4db"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "53fffbe99a7bd6b30f28eab0ed538f9df4c410999d6cc31411d40d9526f1ecf6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32a128fb57db447f0cd16da02c5057249a3737cf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a683ccff525b84d4f9f204075deea84217bf8053f0dc14d0bf433b16ce4dd9cf"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f32edb81a5f17910af752ce9ec64485b64c94c45"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3f76480384ea1c0f6e208aba1a2953d52e8b1e577b6bb6d78d3adffb9aa140dc"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b3c61677259316fa012d7edbf4f2a4cae86f17b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0b4418c94455d073aeb07ce6c1db1388db4554532edf3d6cf63e0e7d46172a91"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96d84d2fb0081b183ee6c5d5336d82eb5c2551c2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bc1be94bfd57cb4eb39da9de4e096534f45d645b1d3b57c6d7dafd18373d6aff"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "366d8814f963b1a5806fab35b8054a27863e3c03"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "22f80c1445028415be7f085996c29d898ad7b988ac1c1f90bf29449b93d76a1e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7876bfb640141715442810023dbafe677a8fae32"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "16f84967b46e7eeea6b250f95a251be9737a03e0a5d689ee68140af78ffd4a22"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2d16c5aa4642435d0819e8c38e772cdee95aa8c"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5773a9ff036d15165a6b29878c94e7830c78f9f51337619030bc8326ce25f24f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "5354f0ac51496f13f3c6a7bdcf397f6e19e8c881"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "5d5702042939af29020bd9684c9fb7382f815dd104d02478dff047aba21b99a2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc58246a69d99d450dcde9d7fca1d9a379429222"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "481b7d8cd39a3fdc1e4088c6ad1c7d8f289c7eab7a0456424ddb4bab2b77bc6f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cb915db0827ea0c8d772bd71744cd699dd433fa"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4dfd24de0b21317824b39964b46338b5137971cccbdf4a7f0dc4d13fcab14e4f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "3d221f2913883525e11f6ba4de2d2158ab3521a6"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "1001263f1e3e6fee6fad30bd47ea6d2ddbd221ee70cd1452afdcce36fb656e17"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a4c6f2cf1c4373957f06bcd59ba275fddbedfe4"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "7376ac1d5a8d5636c5e01ecad50c65520ce337fe6c0cae1393d4f5a621a156ab"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0d8a9ee91c52d56108bf714fcfdfe0b0c0c62aa"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c0d9e72ff47ad160e7e30c8823506d14e70167ed724d928f0051cb88b3a4e378"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43691e9971942a609c2d9b473d210e37b4db8de8"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "587105582443bd9eaea599cb0050fa43c1ac4cd33e878e9e1e8f9d818608ea46"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f8f22b7a7673a28e2d605e0aae5b67730aeaf23"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "fd3fb91fdc3d578de7c910233e4f42f7d9bc9f80e5673260dbba7f8f695c0b0c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "ebe0a5ad442a4e96d57fcc51c6ea20b210ee1e30"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "a0e214086a954273868db8c064c2944364a11f2c7e9d082c16a1470662d80bce"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "467dba09c942f42ff3e4e7cf385c81611f774ba3"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "3eb8f55c1416a7354482e793e5c5d78923e9623795c90cb8e4b20b0fd4283ac6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1+0/HiGHSstatic.v1.8.1.x86_64-w64-mingw32.tar.gz"
