[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "434623e59e53105ecc0b6a0af52461453098507e"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "33ac7a610abcabc270ebba7452964d25232cfeb51ab09c3bd1be5c679f75f7ea"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d44e1d4afa7ec2acbc6e0daf13f925184ce27bbf"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ed4f74c84ba9bf60bca59146c0078df1f2537f36d19c6178d824d4cdbd929afe"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b870dab3ebd93df90810a3a0f004cb20842f4094"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3ced80a51d7791037264b957558b0deab9671f736c0e2802f055d4aaacf4115f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b207b241297ece09bdb78029bf43a6a63db7f5c9"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "75b465d90badcf6f4326fe9a734642059055fa0016068b0d66bd2980e1ea3845"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69c60fd5fba52b9a17ce69d11b113e7aba5535ba"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "20cb476c4595f83538be9ca8adea5b12cfce650595f327dcd9b313be8e93cadd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec3964137064ebb6519047a7b8674df579ca66a1"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "835edad4307e5e375bf69949fc8b3096511caa4fc06ab605a5e2124865c072d6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc8e780af14072c6171fb6d8ce83acadd8613291"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "36e0f297976969fd15c1c9375b7e330266f58a34a208c8bebbf40a1fa4ee2ae0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1320a990f18f1872139c9115789ed73e95f9a3e"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4845c865856a09306f869824726c6e7a8186865c2ffa895cecdb2cf4aecc00e1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "845ff7d857e95ce2ccd238b1b81a31e62885601f"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f7af31968a35378b59cbeb5d21beabc95728d2b1000f9e52c61ba0b0a2cbefdf"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "017859cca239a7b29e7d3126e07330a3fc47ec6b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "008ca13639f4ee5428cfed5ecaf4e0d7110d84da89081a1813689367f700ebee"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b57b5325efa9107288b12e08f5a8c14ba16d75b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "87cc84fcef79245477647556b55d40e154a80ca0b00a9cd76a5d2350433ecf57"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae3d58d916240f7822f8a0503f4a4e988b5f469e"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bda243b0a0ebd6a01a47ace35bd5f7d45250aa865e0f7caac26aa7abafa74af5"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f8c2e6de93a17366c5eb49eb4ede09e4c08bd59"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b5e8395aee48c2ee074fed2c9ad20f36c68d272d60160fa5a021c77c26e60b51"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe9c76df3f59246966c326b2f4731998ac31f5c3"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9ac915695a0c6d9890bf1a73a30d9b434d0e0dbaf195fe87ac451a9e91782eca"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c23b5d15a2f5183548e42cad1fab8548b0869bf0"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "d7a950d540a9cd022522563a0362b634d775f7257bebd0893220693663131922"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb222003a910a5fc538091888a4c256049039b25"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ebb078db02463b6efd16d602e2f4e2f97ac243f686a25e8525fee7b97fc316e0"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c3332ba931a069c38fed0bfd39224108cd47a33"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "859b8eb7d72c810a4de89fa0de700dbe233b4dce037e1c7a8c6bc8b4a7f5ade3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "6ea9a1a2a258bdd1438c8985dc416d52a082476f"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "ed24e599c51213929cf5452745301c6a2f56c319904776882e9f8c3042815771"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d535dfcf68643b9ab8940897e1f0df9ec8d6e9fd"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "69afee3ab9d835b3ecda94244e99cf0c4f0f1428814d448108274fa8e54f51b7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bbfb986075a41c4ca87482a0cace2a8cc7b3cf3"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6c4e7151f6ea532ecc86e49afc11af197f22908e3a0ae68e4625c6bb9cf6d5f9"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "bbd531d0a610705f04eaad50e7fb36070dc2a623"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "c4eb86f3a9f8e0a4e33f86644ad04f07407536d8f19cbbee0fdfb5d376ae2d4e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9008799f32bb3425d56ed90e8eef88e2c9f6852e"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9a91e06cebee07fdee2f651d22c238b950ca32485f399ece9e92733f199a80c4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fb054b727cdeb433d884fc16a66c8fecb994d31"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2879114efc5ad9fb9636a4f725d60369704e6c9cd6faf06dea171f6d6676b2f4"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b3348ccddb942b6038159d048ed2145ff29c996"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "cb5576f93b2f897b6bb94e9451460dddcf2a0c763c150dd0ceb41ee1368db027"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97676af8f21090371197d2cb541dc70e67283c6a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "912eb6fa95fdc826476fffdbac332db0de1230fe126abf59a1e29b807f635cc1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "6a9a31febbc08fde1293d6e785eb974939868199"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "231a6a3ce72ad6c1cb02f94c0aacff6e7247bf57db3fa760f2f4daab60a57338"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "1e07f45291e747f88046b33bd98f42451f251486"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "477c380b1ab1541bf582a2409df500eaaf14cd7f06fc53212f09355c5002e23d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.0+0/HiGHSstatic.v1.7.0.x86_64-w64-mingw32.tar.gz"
