[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "3ffbbd99df4eda831efc3564f9c0a01db5b26163"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "6c537b39f458570dff07b1c2b49492044827cb3526bf95efdc94023f50a5faaa"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea9ff67d55a765245b527990275da926f00286a6"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "4a25137968b5a3369148a4509df17e769105e78355404df958a312ac5a774ce2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ad5f7fbe94eafa10991e15eebfadd9ab0115d1d"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f2ecdef3beb8af772f6f5d2eda53d9dbf7b7ae45f841fcb8665b6337eb68f743"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b1bede106704ec02795b56ab84f4f9e92f556e5"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "3df143a725eecf7054c13979b97b0a4fc6aeb2390c46d46a9e8397915ec2daeb"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1f4aded23af588ed7c4e0ce084ee4984d185eb7"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "1b4723a868b931edee098d0ff6a72ba0dd82e0ee9f1f8c28135231d5288bb9c1"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12d800a69c9778bda4b1e72f5ec059a1dc91cb82"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9b0aecc15cf913bcdfa390e4eed69c70934df7e3e5e11438ed7f56b3e0ccb88a"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "877784ba312c5c149d7ee540f9fea845b0bf9a1b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "aa6e0938ec208195026eb93ce71b4c0392bde533e157a3ea34494171e51b7946"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01564102f33fde2a0b4cd15e982584ea86961b72"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f288c8531c1f70feb54ce4fa78ac1b9874862795eeb7c7ed329f1c8307c6ed86"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79b53e07ab09b1ca1cf5eec0af6fac6a790dcc1f"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c404170b6c0d7804144a5e87a985844d4d1800de762b2375c5de791ec0a4d06f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "518afe6c5510ca0dfe3145326441277e9af2e04a"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "410027a02fd483f660b628896a41dd910421d07632aa4b1e48046d63d0fbfd83"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "405cb68c4c8c231e8105c95ef6b098800529eb7e"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "7e56b15ba36c1b3e08afe85f3e3832ba9d3aa4da141e68c81cedf8ed1cb3d204"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17d332393b1010801e7e5666062aff6ebee4fa0a"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b7c2bda6d80a13c37a99f7bdb3498d7b421788de3573207faf1dfec8b7d44e08"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0777bcea83b6d385a67d390ea1e371db21d4b491"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "6835091678228411e2533005de013c216dc7119cc49c72862c0a7c42b13917b6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a39d26d7aa1af4dca72eed4e1b235da264e0d6b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "c34a52efd6acf06689785aca9c0ffed8347cb30e690ad8ba33ed00c7d0c642d3"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aca4c9b324e789e07bfdf0259c810751a37490c"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "d2dc8c4eef2b2b0fbcac42eba629f49e776a5a8072821fba17389ff9b80aea80"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08a236331acd746b68ef31e24ffb3c10ab38c5fa"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "68f90d3df8fcebab87c61039906c233b61efe2ade34a2b6e29121e42ec03963f"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dfb0e9a501024796ca6d546513504652552a235"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "42fb9e7e5a2b1b1de4a7930bb848257685dfb29c2ab72a6b178ff53ae1851a33"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "a9c572b82c04ff0163348c35aa663d4464aadfd6"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "ec46628dda5113cf78042956522397c3a3be0c1cfc81349a56101f336249d3f6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c527eea2b8615af364c1a0f31ebee6827cdcd344"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f2fdda2fca5edda72ddcb401df57b84d55f036cc9358010fc81b6d3e924e8d00"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4af459d36d92fde2bc7a8b6f75f5c95bbea84522"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "f4d30cc68b1c4feb172b2651d740d046494fac49548fe8d314c79580b18d6b2b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "91f7c1dbacb093808cf173b062973c97f04e1445"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "f4b19376d976a2ed08b3e578c79d91592d6e9241b13cdcf5cc39102888b2ba50"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ecb47a5d321cbdf4bda9dfec58f3bc9eabfe72b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ab2fc3a6d875f1994b03fb1d78647172bc1de8b56529f73e9dd0bba6a104f552"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62ffbb2f32c2b358de9a32b21bda164e1c199370"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "0f4d479a0f4db34aa3399e0821f8d5f9e87fb63e5985ddf24ae79d9d1ee7135b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c70d8084c19265299303e81894e393ecf8c3cb64"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a63841fd538ac4db7a4b07828d6815b3359397e84f410bb6194d3f249953e697"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a76abbd6987df93e0d2d34546320ceb120205f6"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5174fe414a6d5da26535e6a0cfa64f85f363a0046fc0e985ff78b11bb1cd8f70"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "014153c22a41d47045ecbb83aefc683aca0b46f3"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "3da9e5ca9cd9b09652c6a7845812afeadcb7b14a21b827a91d39d168d6f5ac34"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "0e4aa7368bd712f10e5d86becc328cd65d47c335"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "0606a6817ea13a1aef6910bbea2a499600cf97ae38951d8ca5e71fe00e097615"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.6.0+0/HiGHSstatic.v1.6.0.x86_64-w64-mingw32.tar.gz"
