[[HiGHSstatic]]
arch = "aarch64"
git-tree-sha1 = "05a3bf8dd7e1c6d2b149a79fbedf2013a5cb1d8c"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "b17cebb0c2443aaff5a16c8b9e457309203e1e056211847918ce5d807eed7ac9"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.aarch64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07c5dfbf0622da1a2d239786f48e5de9c930b2ad"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9a879e3da023c37f60cf143f049012078d4a30ac2287b1859841d3143b93734e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.aarch64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e27017fc6a789bdfa24017671db89b1a1906dd"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ac4fbbc16541e21b41efda7695a5d6a2a264fb3d2a3baae6e6e962bd33f27d73"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9025a767c1ac525a8ce851f63a370eaf11c76432"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9c96feedbbae667b5bc088376109a7f8c64dc67f69dae95d2f2a5c4da18640f9"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.aarch64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae0aa2609bc388c46963e8c6eb4b9a5e29b0f9cf"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "888f8a397817fb420a91fa3e3ce622e09544d3371bea6245063cbcd1484c4842"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.aarch64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "546550daac87e38dd2db34ceb1bac9c3edeeb0e2"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "5b4fa6f735e264cfade0c105054774774cbf50b671cec7ae86458383ffa01be7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de4a87319d6ce0a14384e57a42203d27767b5b34"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "a31a81e349efd226329c12cd9e3d4a0794a21563507913b233fe25404a8f4e85"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d648041b0b361863799ab936edaba7594e49cd65"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "faac976fee00f0ed429a1e93710db7cda9294c4b276023b58233616045b6c697"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dcad4ff210b59068e14b91eaf98d585d5a0f701"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "ff80b4515dde881989c96344c6a94e54744b6505b3c106924aa8163918d7ff63"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d6ff9781731c2d7e8baa7d79704faec1a5f5da9"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "176720166e6c2d64b8bf847234b490a195c9eb10a32869615c5a5f09024e5dbf"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b36a7c26d7ffae7fd7aab0eb1df2fd4b126f779c"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "98b4a325667b8bda35bb440b8dec69150624f9bf263e6deb8e170e61fc834bb6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "425742fa16bfd0f7028328da88a880dca942b75d"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "31000266fc5f0723afb9df364066ee0f36d4386500352052f0844ff6776e314c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8138ef905fc7dcaac6de48e4dcd49f88724b3351"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "44736577827eb085cd5f7be106abcfafecb642a64df975a39da8f1842c2955bd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51b6ccd9ba3d137a27fe988fae1a024ba50ccb02"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "b477f5f62b35851b2db8094ad6607051099173eaecd1f0866406199db5d4a739"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.i686-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6a0fad4164a245ee405682b95eebf54509c271b"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "14a7ddaa99c99a0e4059008b91944a34efec58690eeb60f1f259b3bb518296c7"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.i686-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a20b015594053e3c59fed3aaaa8cc56040349b0b"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "cc46ae90543e8a66b497405a28f629f9529bb8b03213aada4d714b400eefe1b6"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.i686-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b0a390cc78520ab4ee8f5035f31e85c7b88b5ce"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "555898537d48226da1316f8c84b79e67a380b6929f81384b431929f9cb9fc53c"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.i686-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "i686"
git-tree-sha1 = "41ce334a67422372408f2a856789b696d4fcabe5"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "ee250f9031c30e1809a0310b41cda92f51b7d8acb8a7a59f79de526bb38aff46"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.i686-w64-mingw32.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54960be6c82a2a594a3db1ded6c691db724c423c"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9f64325436bd1192b8377b9ef62f47ed96868ad5c0f1efb7f4aca5d34205bbdd"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c54510b764e571eaca102323d9b2736604f108c7"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "9909dbe30c0ba3cac888f5a62d461c0754221615ea8f9daab2fc95bc829d63a2"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "5ab9e57ff792f90e223d52e0364baaccd45d8230"
os = "macos"

    [[HiGHSstatic.download]]
    sha256 = "4fb28824f21305ab6a4e4de40a8e6e47ee83855c0b5637e29fec91d7e1b67a5b"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-apple-darwin.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe1084a97abc5a1834339eba3f5d45d6e38eabcb"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "2f47175067b838790b08e38416e3c08bcd3ac4af9a710f8141a5778fc95140aa"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-linux-gnu-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c3c8e943ea4cb408f13be1a1ffbfc1312eb97ba"
libc = "glibc"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "e7c4884748eaeeecca328062f80e317c5b5b75c0b85e2aa7bd338d7f1b593859"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97cd231357e93e07024c913f4d1239dad052af97"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "8a42f4b24e768852a673daaebc6d7d4afb541e53089a1e425a2f000754821d9e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-linux-musl-cxx03.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10ec0c7bb54ef1a991205022523633516551e507"
libc = "musl"
os = "linux"

    [[HiGHSstatic.download]]
    sha256 = "bf11b4beefaafbef07ee9bc207b49b74a2f8d149a75ea434cb48ff7544661d1e"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-linux-musl-cxx11.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "91d995919fd702f5181656709eb3c41315200645"
os = "freebsd"

    [[HiGHSstatic.download]]
    sha256 = "93241475cdc73e4f2402bb947f27f8e73a1c1d714c9f6d4cd3509fad82f55bf8"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-unknown-freebsd.tar.gz"
[[HiGHSstatic]]
arch = "x86_64"
git-tree-sha1 = "fe54fdaca06708c33891dea28fbca8dd035a2c4f"
os = "windows"

    [[HiGHSstatic.download]]
    sha256 = "99d5465d665b2c64fdad579a05ad4fc00c3fb0871f3348898a0f39df4d09411d"
    url = "https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.7.2+0/HiGHSstatic.v1.7.2.x86_64-w64-mingw32.tar.gz"
